### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by MrkarlosM** [realisticattorney/YoutubePageRepo#1]
This is the first Issue.

After every day, I guess you should do a pull request so we can review your code.

**Comment by abongsjoel** [comment]
Try to make use of HTML5 syntax such as <header>, <section> and <footer>

In my opinion, instead of creating a separate <div> just the container, you can just the .container class and add it to where necessary

**Comment by abongsjoel** [comment]
Try to make use of HTML5 syntaxes such as header, section, and footer

In my opinion, instead of creating a separate div just the container, you can just the .container class and add it to where necessary

**Comment by AntonyOtero** [comment]
The images aren't working because you need to use relative paths. Instead of using the following:
```html5
src="C:\Users\ADMIN\Desktop\Youtube\Images\5.png"
```
You need to create a folder in your projects for all your icons and images and use a relative link like the following:
```html5
src="images/5.png"
```

**Comment by MrkarlosM** [comment]
You should use a separate folder for the styles and for the media. Like:

src/images
src/CSS

Inside them, you can save your styling sheet and images, icons, etc.

**Comment by MrkarlosM** [comment]
Don't forget that the correct indentation for a css file is done with two spaces, "not tab spacing".
![image](https://user-images.githubusercontent.com/33767393/97016304-33590a00-1512-11eb-949f-ead0ab892189.png)
